spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bcsd?serverTimezone=Asia/Seoul
    username: root
    password: kk25781179@@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true