spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bcsd?serverTimezone=Asia/Seoul # 본인의 환경에 맞게 수정한다.
    username: janoogwan39
    password: dnldtkd15^^
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: off
    show-sql: true
    open-in-view: false