spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bcsd?serverTimezone=Asia/Seoul # 본인의 환경에 맞게 수정한다.
    username: janoogwan39 # 본인의 환경에 맞게 수정한다.
    password: dnldtkd15^^ # 본인의 환경에 맞게 수정한다.
    driver-class-name: com.mysql.cj.jdbc.Driver
